In [8]:
# PARÁMETROS
# ==================== PARÁMETROS ====================
ESQUEMA = 'manejo_forestal'
TABLA = 'DivAdmBos_Arbol'
# ==================== PARÁMETROS ====================

BASE_DE_DATOS = 'forestal_pre_actualizado'

In [11]:
import geopandas
import pandas as pd
from sqlalchemy import create_engine, inspect
from geoalchemy2 import Geometry


engine = create_engine(f'postgresql://postgres:ficticio@200.48.19.4:9006/{BASE_DE_DATOS}')

def get_sql_query(tabla: str, esquema: str = 'public') -> str:
    sql = f"SELECT * FROM {esquema}.{tabla}"
    return sql

# BASE DE DATOS

In [13]:
inspector = inspect(engine)
columns = inspector.get_columns(TABLA, schema=ESQUEMA)
df_table = pd.DataFrame(columns)
df_table

,name,type,nullable,default,autoincrement,comment
0,id,BIGINT,False,"nextval('manejo_forestal.""DivAdmBos_Arbol_Id_S...",True,Codigo identificador del objeto
1,NUMARB,"NUMERIC(5, 0)",False,None,False,Numero del arbol
2,NUMUT,"NUMERIC(3, 0)",False,None,False,Numero o codigo de unidad de trabajo
3,NUMPC,VARCHAR(10),False,None,False,Numero de parcela de corta
4,NUMBLO,VARCHAR(10),True,None,False,Numero del bloque asociado
5,NUMFAJ,"NUMERIC(1, 0)",True,None,False,Numero de faja
6,CODARB,VARCHAR(50),True,None,False,Codigo del arbol
7,TIPOTH,"NUMERIC(1, 0)",False,None,False,Tipo de titulo habilitante
8,NROTTH,VARCHAR(100),False,None,False,Numero de tipo de titulo habilitante: Contrato...
9,CODESP,VARCHAR(8),False,None,False,Codigo de la especie
10,NOMCOM,VARCHAR(100),False,None,False,Nombre comun de la especie
11,NOMCIE,VARCHAR(100),False,None,False,Nombre cientifico de la especie
12,FAMILI,VARCHAR(100),False,None,False,Familia de la especie
13,GRUPOC,VARCHAR(100),False,None,False,Grupo comercial de la especie
14,COORES,"NUMERIC(10, 4)",False,None,False,Coordenada Este-X del arbol (m)
15,COORNO,"NUMERIC(11, 4)",False,None,False,Coordenada Norte-Y del arbol (m)
16,CALFUS,"NUMERIC(1, 0)",False,None,False,Calidad de fuste del arbol
17,CONDIC,"NUMERIC(1, 0)",False,None,False,Categoria de condicion
18,CONDSA,"NUMERIC(1, 0)",False,None,False,Categoria de campo
19,CITES,"NUMERIC(1, 0)",False,None,False,Indica si el arbol es de tipo CITES
20,ESTADO,"NUMERIC(1, 0)",False,None,False,Estado de arbol
21,FECEST,DATE,False,None,False,Fecha de estado de arbol
22,DAP,"NUMERIC(7, 2)",False,None,False,Diametro a la altura del pecho (cm)
23,ALTCOM,"NUMERIC(7, 2)",False,None,False,Altura comercial (m)
24,SUPABA,"NUMERIC(7, 2)",False,None,False,Superficie basal (m2)
25,VOLCOM,"NUMERIC(7, 2)",False,None,False,Volumen comercial (m3)
26,CATIPO,"NUMERIC(1, 0)",False,None,False,Categoria de referencia de actividad
27,ESTSUP,"NUMERIC(1, 0)",False,None,False,Estado de supervision
28,NUMINF,VARCHAR(50),True,None,False,Numero de informe de inspeccion o supervision ...
29,FECINF,DATE,True,None,False,Fecha de informe
30,geom,"geometry(POINT,32719)",False,None,False,Geometria que representa el objeto
31,FUENTE,VARCHAR(100),False,None,False,Entidad generadora de la informacion
32,DOCREG,VARCHAR(100),False,None,False,Documento o informe tecnico que avala el regis...
33,FECREG,DATE,False,None,False,Fecha de registro del objeto en la base de dat...
34,OBSERV,VARCHAR(255),True,None,False,Cualquier observacion o referencia
35,ZONUTM,"NUMERIC(2, 0)",False,None,False,Zona UTM
36,ORIGEN,"NUMERIC(1, 0)",False,None,False,Origen del objeto